### ISSUE TITLE
I have discovered a couple issues

### ISSUE THREAD

**Issue by senpaizuri3** [trigger-death/GrisaiaExtractor#2]
The first may be a Windows-related issue but I am not familiar with this error.
[The data area passed to a system call is too small. (Exception from HRESULT: 0x8007007A)](https://i.imgur.com/rPhADyZ.jpg) If it helps, the game I tried extracting from was Grisaia no Meikyuu.

The second issue is that sometimes it [stops converting and closes without error nor confirmation](https://streamable.com/zy9sp) when converting hg3 files. It is consistent on when and where it crashes but not every game has hg3 files that crash upon attempting to convert.

If it also matters, I am running the application on a Windows 10 x64 laptop.

**Comment by trigger-segfault** [comment]
Could you also tell me where you acquired Grisaia no Meikyuu? (Steam, Denpasoft, or just *other* if you don't want to say). And what language?
Are you using any patches on the game that modifies the `image.int` file?

I'm trying to guess what the first issue may be, my first thought is the fact that I forgot to compile the extractor for x86, because that's what the underlying `asmodean.dll is using`, currently it is set to *Any CPU* which means that your computer is trying to run in x64, while mine, although 64-bits, may be trying to run in x86. But this doesn't make sense because a different error should be thrown.

How often does this first issue occur? Is it also consistent? I'd like to look at the `image.int` file if you are alright with sending it. Contact me via **Reddit:** [/u/trigger_death](https://www.reddit.com/user/trigger_death/) or **Discord:** `trigger_death#3846` for that. Alternatively, I can just try to write something that's much more verbose with what's happening in the code to see if we can lock down where it occurs, it should be showing the call stack which is strange.

As for the hg3, could you send the afflicted file that it hangs on? Since it's consistent I can easily look at what's causing the problem.

**Comment by trigger-segfault** [comment]
Actually there should be a `GrisaiaExtract.log` file. Try to reproduce the error again and then show me the file. Unfortunately I did something stupid and made it so it clears the log after each program execution. :\

This would help answer what went on with the first issue.

**Comment by senpaizuri3** [comment]
To be honest I don't remember how I got it, but I don't think I have ever added any additional patches to it myself. (It has been quite a while since I installed it.) I can give you any files you may need or screenshot the contents of my folder(s) if needed.

The first issue is not consistent. I just tried it now again and I got stopped at a different part. [Image](https://i.imgur.com/rWnQsmZ.jpg)
[`image.int`](https://mega.nz/#!d4gmWAAJ!87Jnk6iYOCk9fvElrWo0i7kqoT0GGUNOZDi9iya8hdA) (no longer available)

The file was [caution1.hg3](https://cdn.discordapp.com/attachments/234822249331294208/527534423923752960/caution1.hg3) from Grisaia no Senritsu.

Edit: This is the log's contents after doing that:
```log
[12/26/2018 12:26:29 PM] Extracting image.int
Game: Grisaia no Meikyuu
[12/26/2018 12:26:48 PM] Error: The data area passed to a system call is too small. (Exception from HRESULT: 0x8007007A)
Game: Grisaia no Meikyuu
System.Runtime.InteropServices.COMException (0x8007007A): The data area passed to a system call is too small. (Exception from HRESULT: 0x8007007A)
   at System.StubHelpers.ValueClassMarshaler.ConvertToNative(IntPtr dst, IntPtr src, IntPtr pMT, CleanupWorkList& pCleanupWorkList)
   at GrisaiaExtractor.Asmodean.Exkifint.DecryptEntry(KIFENTRY& entry, UInt32 fileKey)
   at GrisaiaExtractor.Asmodean.Exkifint.Run(Stream stream, String intFile, String exeFile, String outputDir, ExkifintCallback progress)
   at GrisaiaExtractor.Asmodean.Exkifint.Run(String intFile, String exeFile, String outputDir, ExkifintCallback progress)
   at GrisaiaExtractor.Extracting.ExtractInt(String inputDir, String intFile, String exeFile, String outputDir, ExkifintCallback progress)
   at GrisaiaExtractorConsole.Program.ExtractIntFile(IntArgs args, LogInfo log)
```

**Comment by trigger-segfault** [comment]
Try this version of Grisaia extract to see if the Meikyuu issue pops up anymore, in the mean time I'll take a look at the hg3 issue.

**[GrisaiaExtract_x86.zip](https://github.com/trigger-death/GrisaiaExtractor/files/2710645/GrisaiaExtract_x86.zip)**

**Comment by senpaizuri3** [comment]
I tried that (in another folder location) and get [the same error as the previous instance](https://i.imgur.com/W42G2GD.jpg). (I also edited my last comment to contain my `image.int` file.)

**Comment by trigger-segfault** [comment]
Alright thanks. I've got the file, and you can remove the download now.
The hg3 issue is solved, there was a tag called `"imgmode"` when I was checking for tags that started with `"img"` instead of regex `"img\d+"`

**Comment by senpaizuri3** [comment]
Alright. About when will the source code be changed and a new release be added? Or will you wait to fix what was going with `image.int` before changing the source here and/or releases?

**Comment by trigger-segfault** [comment]
I'll release the `hg3` fix now. and update the source. I'm going to check the hashes of the `image.int` files because they're the exact same byte count, I'm wondering if the file key in Grisaia2.bin is different, but that would mean the images couldn't be converted properly. Have you tried converting the `hg3` images extracted from Grisaia no Meikyuu during failure?

**Comment by trigger-segfault** [comment]
Okay, so the `image.int` files are in fact the same. Sorry for making you go through with the upload. (By the way, you really should remove the download link for it).

**Comment by senpaizuri3** [comment]
I tried just now and the hg3 files have been converted without error. There are only 562, of course, but no errors emerged from extracting them. I will also delete the file from Mega (since people can see comment history if I edit it away anyway).

**Comment by senpaizuri3** [comment]
So would you need my binary file? Or did you also receive the same error as I did?

**Comment by trigger-segfault** [comment]
I guess I'll take it while we're both still present in the conversation right now in case I do need it. I'll keep retrying Meikyuu to see if I get the error, but I'm unsure because I've done the int extraction for each game I own probably about 10 times over.

**Comment by senpaizuri3** [comment]
[Here you go, then.](https://cdn.discordapp.com/attachments/426043379239878667/527554319747383321/Grisaia2.bin)

**Comment by trigger-segfault** [comment]
Same MD5 hash unfortunately, *or fortunately*. Whatever is causing the issue seems to be a difference between our systems. Would you mind listing what versions of .NET Framework you have installed with this? I'm looking, anything 4.6.1 or later.

I have one other idea to check for before I'll resort to StackOverflow for the error. The code that calls this error is native so there's no source for it to see what it means.

**Comment by senpaizuri3** [comment]
I have .NET Framework 4.7.2, so I should be fine.

**Comment by trigger-segfault** [comment]
Also, if you haven't noticed, the `hg3` fix is up. This is still so strange because it doesn't happen every time...

**Comment by senpaizuri3** [comment]
I am confirming the hg3 fix works (just for the sake of confirming). However, most of them are coming off as a part of the `Unidentified` folder, likely due to not considering characters take place exclusively in this game like Major Isabella Fitzgerald (`iza`), Marion Garland (`mro`), and Ramon Noboa (`nob`) for sprites. There are also some BGs with the prefix `bgt` which aren't placed in the background folder. The CGs are given the prefix `evt`, which are also placed in `Unidentified`. You can have them in a Story/CG like you do Afterglow (Zankou).

Speaking of Afterglow, I just got a strange issue. I tried extracting the hg3 files (which I got all just fine), but an error came up. The error didn't even save in the log. The error is about [trying to read or write with protected memory](https://i.imgur.com/F3yUZa9.jpg). My folders are not read only, and certainly not some random file. (Both times I try, it stops at that file with that error, and again the log doesn't store it.) I don't know what's up here.

Note: I have to turn off my laptop to charge so if I don't respond for a few hours, that's why.

**Comment by trigger-segfault** [comment]
Based on the console font it looks like you're using a locale that isn't English. I read a few posts saying the first error we talked about may be caused by that. What I did is switched all character arrays that transfer between native code into byte arrays.

**[GrisaiaExtract_bytes.zip](https://github.com/trigger-death/GrisaiaExtractor/files/2710870/GrisaiaExtract_bytes.zip)**

For the categorization, can you make a new issue?

As for the final issue, maybe there's some memory leaks or out of bounds access going in the native code. I'll have to investigate that further. Unfortunately Zankou and Senritsu are the *only* games I don't own at the moment so it's not so straight forwards to test.

One last ditch effort is to try changing your locale to English to see if it solves either of the problems, there's a problem in of itself it that fixes things, but at least that'll help narrow things down.

**Comment by senpaizuri3** [comment]
I changed by "Language for non-Unicode programs" to English and restarted my laptop, and that did fix the Meikyuu image extraction. The newfound issue of memory stuff still persists both using the original and the one you uploaded in your comment. Since that was unrelated to the original points in this issue and both said original points were solved (and this is dragging in comments tbh) should I close this issue and make a new issue about Zankou?

**Comment by trigger-segfault** [comment]
Yes, for the memory leak, but also keep this point open, because changing the Locale or language should't have need to be a fix. Did you test if the `bytes` upload fixed the first issue too? Because it was only meant to fix the first issue.

Although in the future you probably should have made a separate issue for the first two issues, but it's not really a big deal. So don't worry about it.

**Comment by senpaizuri3** [comment]
That extractor stopped at `bom_s.hg3` with Japanese locale (what it was before switching to English) when using the extractor in the bytes zip.

**Comment by trigger-segfault** [comment]
Alright, one last tackle of the locale issue. This changes the culture and locale of the native and C# dlls to "en-US", For some reason or other, I couldn't reproduce the issues by setting the locale to "jp-JP" programmatically so I'm worried that this may not help. Your current locale is "jp-JP" correct? If not, let me know what it is so I can test that.

This also *should* now report any instances in the hgx2bmp conversion where memory is being accessed or written out of range.

**[GrisaiaExtract_CultureInfo+LeakReporting.zip](https://github.com/trigger-death/GrisaiaExtractor/files/2713246/GrisaiaExtract_CultureInfo%2BLeakReporting.zip)**

**Comment by senpaizuri3** [comment]
My current locale is jp-JP, yes. After downloading and using the contents of the zip and keeping it at that locale, I got an [error stating `image.int` isn't a valid INT file](https://i.imgur.com/0aJKgcy.jpg).

**Comment by trigger-segfault** [comment]
Just my luck... I forgot to switch the build to Release and ended up uploading a broken version. Sorry about that.

**[GrisaiaExtract_CultureInfo+LeakReporting_fixed.zip](https://github.com/trigger-death/GrisaiaExtractor/files/2713555/GrisaiaExtract_CultureInfo%2BLeakReporting_fixed.zip)**

**Comment by senpaizuri3** [comment]
The error of being too small persists and ends at bg_etc01 (561/94240). [Image](https://i.imgur.com/p3oNgEp.jpg)

**Comment by trigger-segfault** [comment]
Alright, I’ll resort to Stack Overflow at this point, but tell me what the error log shows when you run this against the third problem. Assuming the issue is memory leaks when reading the hg3 files, the log will list the file with each leak and state a numeric location in code where the leak occurred. It would also be helpful to know which file is associated with the error.

**Comment by senpaizuri3** [comment]
Sure. Here you go.
```log
[12/27/2018 6:53:11 PM] Extracting image.int
Game: Grisaia no Meikyuu
[12/27/2018 6:53:28 PM] Error: The data area passed to a system call is too small. (Exception from HRESULT: 0x8007007A)
Game: Grisaia no Meikyuu
System.Runtime.InteropServices.COMException (0x8007007A): The data area passed to a system call is too small. (Exception from HRESULT: 0x8007007A)
   at System.StubHelpers.ValueClassMarshaler.ConvertToNative(IntPtr dst, IntPtr src, IntPtr pMT, CleanupWorkList& pCleanupWorkList)
   at GrisaiaExtractor.Asmodean.Exkifint.DecryptEntry(KIFENTRY& entry, UInt32 fileKey)
   at GrisaiaExtractor.Asmodean.Exkifint.Run(Stream stream, String intFile, String exeFile, String outputDir, ExkifintCallback progress)
   at GrisaiaExtractor.Asmodean.Exkifint.Run(String intFile, String exeFile, String outputDir, ExkifintCallback progress)
   at GrisaiaExtractor.Extracting.ExtractInt(String inputDir, String intFile, String exeFile, String outputDir, ExkifintCallback progress)
   at GrisaiaExtractorConsole.Program.ExtractIntFile(IntArgs args, LogInfo log)
```

**Comment by trigger-segfault** [comment]
No, by the third issue, I meant the access violation during hg3 extraction of Grisaia no Zankao. I’ve been trying to solve both problems simultaneously.

**Comment by senpaizuri3** [comment]
It is not being added to the log. All I am getting is the message saying the game and what I'm doing. [Image](https://i.imgur.com/9U7CBqm.jpg)

**Comment by trigger-segfault** [comment]
*Sigh*, this is difficult. One last area I can check is if the rgba buffer isn’t being given the correct size and thus causing Gdi to throw this error. I’ll probably try to pick up Zankou and Senritsu in the next few days so it will make testing this easier. I guess I can also try fooling around with my own locale to test the issues myself.

Could you send me ev506a.hg3 so I can test it myself? It’s consistent with the file so at least that’s good.

**Comment by senpaizuri3** [comment]
It actually hasn't been as consistent as you might think. It has stopped at only 2 files (which are sequential to one another), so I'll post both of those. [ev506a.hg3](https://cdn.discordapp.com/attachments/426043379239878667/528209984517963776/ev506a.hg3) | [ev506aL.hg3](https://cdn.discordapp.com/attachments/426043379239878667/528209999474982962/ev506aL.hg3)

By the way, I noticed that there is already an [ev506aL.png](https://cdn.discordapp.com/attachments/426043379239878667/528210740469825547/ev506aL.png) in the Raw folder. (I have the default output paths, and that is the only output image from raws.) [Screenshot](https://i.imgur.com/iqkTjJq.jpg)
Despite me bringing it up, don't pay too much mind to it. I realize now that it seems to just be a corrupted image file from not being able to extract it fully then move it. I can tell that it's a corrupted image because it cannot be uploaded to imgur due to not be able to process it. (Discord does its best.)

**Comment by trigger-segfault** [comment]
Thanks. And damn, I was hoping I could simulate the locale issue with NTLEA but no luck even there. Constantly restarting is not gonna be fun.

**Comment by trigger-segfault** [comment]
There we go! Managed to solve *both* issues.
* **Issue 1:** I cheated and just made it so I wasn't passing any characters through P/Invoke. This completely solves the problem... but I'm still really unhappy that the problem exists in the first place. *See Figure 1.*
* **Issue 3:** The images had a `DepthBits` of 24, I was surprised since no other image in the game bothered to do that. Depth bits is now accounted for (at least for 32 and 24).

*(Figure 1: I'm cheating and passing `KIFENTRY.Data` to P/Invoke instead of KIFENTRY.)*
```cs
private struct KIFENTRY {
    [MarshalAs(UnmanagedType.ByValArray, ArraySubType = UnmanagedType.U1, SizeConst = 64)]
    public char[] FileNameRaw;
    public KIFENTRYDATA Data;
    public uint Offset {
        get => Data.Offset;
        set => Data.Offset = value;
    }
    public int Length {
        get => Data.Length;
        set => Data.Length = value;
    }
    //public uint Offset;
    //public int Length;
}
private struct KIFENTRYDATA {
    public uint Offset;
    public int Length;
}
```

I'm going to spend a little more time to see if I can properly reproduce the locale bug and then I'll upload the fixes either way. Thanks for your help! 👍

**Comment by senpaizuri3** [comment]
You're welcome. I only know some technical stuff but I don't know programming. (I only know LUA and Batch scripting and that's it.) So long as you got it to work that's good. :p

**Comment by trigger-segfault** [comment]
The offending file was `"b‚‡62t.hg3"` (after unobfuscation). In Japanese locale, these two offending characters would end up being read as one single character, making it larger than a single-byte character. So the program was complaining that it couldn't fit the character into the array when passing it with P/Invoke. The offending character that was created was actually the full-width character `"ｇ"`. Dev team must have messed up with that filename. I'm deciding to make sure all filenames are output with the correct Japanese encoded characters because at least then it'll make a bit more sense than `"‚‡"`.

*As is the usual, terrible error explanations for what was actually going on.*

**Comment by trigger-segfault** [comment]
Can you confirm everything works for you with the latest release? I was able to reproduce and fix all the errors, but just want to make sure.

**Comment by senpaizuri3** [comment]
The fix works fine from my extraction so far. The extraction of Meikyuu at 80% now (not yet converting) and since it hasn't given me the error by now it probably never will. I also previously extracted Zankou just fine.
